#!/usr/bin/env bats
# End-to-end tests for pre-commit-documentation.sh with a stubbed claude CLI.

load helpers/common

setup() {
 make_repo
 install_claude_stub
 HOOK="$REPO/.claude/scripts/pre-commit-documentation.sh"
}

# Run the hook the way Claude Code does: tool-call JSON on stdin, no GIT_INDEX_FILE.
run_as_claude_hook() {
 local json
 json=$(jq -n --arg cmd "$1" '{tool_input: {command: $cmd}}')
 run env -u GIT_INDEX_FILE bash "$HOOK" <<< "$json"
}

stage_change() {
 mkdir -p src
 echo "class Order {}" > src/Order.java
 git add src/Order.java
}

@test "Claude hook: a git commit generates, stages and marks the doc" {
 stage_change
 run_as_claude_hook 'git commit -m "Add order"'
 [ "$status" -eq 0 ]
 [ "$(head -1 docs/technical/order-status-transition.md)" = "# Order Status Transition" ]
 git diff --cached --name-only | grep -qx "docs/technical/order-status-transition.md"
 [ -f "$(git rev-parse --git-path docs-hook-done)" ]
}

@test "Claude hook: a non-commit Bash call does nothing" {
 stage_change
 run_as_claude_hook 'grep "git commit" README.md'
 [ "$status" -eq 0 ]
 [ ! -f "$STUB_LOG" ]
 [ ! -d docs ]
}

@test "Claude hook: staging inside the commit command is blocked" {
 run_as_claude_hook 'git add . && git commit -m "x"'
 [ "$status" -eq 2 ]
 [[ "$output" == *"git add runs before git commit"* ]]
}

@test "Claude hook: nothing staged does nothing" {
 run_as_claude_hook 'git commit -m "x"'
 [ "$status" -eq 0 ]
 [ ! -f "$STUB_LOG" ]
}

@test "Claude hook: missing jq skips instead of documenting every Bash call" {
 stage_change
 local bin="$BATS_TEST_TMPDIR/nojq"
 mkdir -p "$bin"
 for cmd in bash git perl pgrep cat mktemp date rm dirname basename; do
   ln -sf "$(command -v "$cmd")" "$bin/$cmd"
 done
 ln -sf "$STUB_BIN/claude" "$bin/claude"
 run env -u GIT_INDEX_FILE PATH="$bin" "$(command -v bash)" "$HOOK" <<< '{"tool_input":{"command":"ls"}}'
 [ "$status" -eq 0 ]
 [[ "$output" == *"jq is not installed"* ]]
 [ ! -f "$STUB_LOG" ]
}

@test "Git for Windows: the hook re-runs itself inside WSL" {
 stage_change
 cat > "$STUB_BIN/uname" <<'STUB'
#!/bin/bash
echo MINGW64_NT-10.0
STUB
 cat > "$STUB_BIN/cygpath" <<'STUB'
#!/bin/bash
echo "WIN:${!#}"
STUB
 cat > "$STUB_BIN/wsl.exe" <<'STUB'
#!/bin/bash
printf '%s\n' "$@" > "$BATS_TEST_TMPDIR/wsl-args"
exit 7
STUB
 chmod +x "$STUB_BIN/uname" "$STUB_BIN/cygpath" "$STUB_BIN/wsl.exe"
 run env GIT_INDEX_FILE=.git/index bash "$HOOK" < /dev/null
 [ "$status" -eq 7 ]
 [ "$(sed -n 5p "$BATS_TEST_TMPDIR/wsl-args")" = "_" ]
 [ "$(sed -n 6p "$BATS_TEST_TMPDIR/wsl-args")" = "WIN:$HOOK" ]
 [ "$(sed -n 7p "$BATS_TEST_TMPDIR/wsl-args")" = "WIN:.git/index" ]
 [ ! -f "$STUB_LOG" ]
 [ ! -d docs ]
}

@test "native hook: a git commit includes the generated doc" {
 ln -sf "$HOOK" .git/hooks/pre-commit
 stage_change
 git commit -qm "Add order"
 git show --name-only --format= HEAD | grep -qx "docs/technical/order-status-transition.md"
}

@test "native hook: git commit -a documents the tracked changes it stages" {
 ln -sf "$HOOK" .git/hooks/pre-commit
 echo "change" >> README.md
 git commit -qam "Update readme"
 git show --name-only --format= HEAD | grep -qx "docs/technical/order-status-transition.md"
}

@test "native hook: git commit -F - keeps the message read from stdin" {
 ln -sf "$HOOK" .git/hooks/pre-commit
 stage_change
 echo "Message from stdin" | git commit -q -F -
 [ "$(git log -1 --format=%s)" = "Message from stdin" ]
}

@test "native hook: skips a commit the Claude hook already documented" {
 ln -sf "$HOOK" .git/hooks/pre-commit
 stage_change
 run_as_claude_hook 'git commit -m "Add order"'
 : > "$STUB_LOG"
 run git commit -m "Add order"
 [ "$status" -eq 0 ]
 [[ "$output" == *"already generated by the Claude Code hook"* ]]
 [ ! -s "$STUB_LOG" ]
}

@test "Claude hook: a commit in another repository is left alone" {
 stage_change
 local other="$BATS_TEST_TMPDIR/other"
 git init -q "$other"
 run_as_claude_hook "cd $other && git commit -m \"init\""
 [ "$status" -eq 0 ]
 [[ "$output" == *"does not run in"* ]]
 [ ! -f "$STUB_LOG" ]
 [ ! -d docs ]
 [ ! -f "$(git rev-parse --git-path docs-hook-done)" ]
}

@test "Claude hook: a commit from a subdirectory of this repository is documented" {
 stage_change
 run_as_claude_hook 'cd src && git commit -m "Add order"'
 [ "$status" -eq 0 ]
 [ -f docs/technical/order-status-transition.md ]
}
