#!/bin/bash
# Pre-commit hook that generates/updates technical documentation for the staged changes,
# then stages the doc so it travels in the same commit.
#
# Runs as a Claude Code PreToolUse hook (.claude/settings.json) and/or as a native git
# pre-commit hook. Install the native hook once per clone:
#   printf '#!/bin/bash\nexec "$(git rev-parse --show-toplevel)/.claude/scripts/pre-commit-documentation.sh" "$@"\n' > .git/hooks/pre-commit
#   chmod +x .git/hooks/pre-commit
# Use this wrapper, not a symlink: a symlink made in WSL (absolute /mnt/c/... target) cannot
# be followed by Git for Windows (e.g. IntelliJ), which fails with "cannot spawn .git/hooks/pre-commit".
# With both installed, a commit documented by the Claude Code hook is skipped by the native one.
# Under Git for Windows (IntelliJ, VS Code on Windows) the hook re-runs itself inside WSL,
# where its dependencies are installed.
#
# Under Claude Code, a commit that also stages files in the same command (git add … && git
# commit, -a/-i/-o/-p, paths) is blocked (exit 2): the hook runs before the command and
# cannot see what it will stage. A commit that runs in another repository (cd other &&
# git commit, git -C other commit), or whose directory cannot be determined, is skipped.
#
# Where the logic lives (lib/):
#   config.sh        settings (DOC_* environment variables) and dependency checks
#   hook_context.sh  Claude Code vs native hook; parsing the git commit command
#   git.sh           staged diffs and the "already documented" marker
#   maven.sh         Maven modules and project names
#   targets.sh       which docs folder each change goes to; parallel batches
#   doc_writer.sh    title → filename → generate/update → write, per target
#   claude.sh        claude CLI calls and validation of their output
#   process.sh       time budget, per-call timeout, process-tree cleanup
#   ../prompts.sh    the prompt texts
#
# Dependencies: claude CLI (authenticated), jq, perl, pgrep; timeout (GNU) or gtimeout recommended.
# Tests: bats .claude/scripts/tests   (bats-core: https://github.com/bats-core/bats-core)

# ── Git for Windows: run the hook inside WSL ─────────────────────────────────
# The claude CLI, jq and pgrep are installed in WSL only. Git runs hooks from the worktree
# root, which wsl.exe maps to /mnt/c/...; the script and index paths are passed as Windows
# paths and converted with wslpath. bash -l puts ~/.local/bin (claude) on PATH. Stdin is
# git's and is not forwarded. Without wsl.exe, the dependency guard below skips the docs.
case "$(uname -s)" in
 MINGW*|MSYS*|CYGWIN*)
   if command -v wsl.exe >/dev/null 2>&1; then
     export WSLENV="${WSLENV:+$WSLENV:}DOC_MAX_DIFF_BYTES:DOC_TIME_BUDGET:DOC_CALL_TIMEOUT:DOC_PARALLEL:DOC_FAST_MODEL"
     exec wsl.exe -e bash -lc 'GIT_INDEX_FILE=$(wslpath -u "$2") exec "$(wslpath -u "$1")"' _ \
       "$(cygpath -aw "$0")" "$(cygpath -aw "${GIT_INDEX_FILE:-.git/index}")" < /dev/null
   fi
   ;;
esac

HOOK_START_DIR=$PWD   # a Claude Code command's cd / git -C paths are relative to this
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
[ -n "$REPO_ROOT" ] || exit 0
cd "$REPO_ROOT" || exit 0

SCRIPTS_DIR="$REPO_ROOT/.claude/scripts"
for module in config process hook_context git maven claude doc_writer targets; do
 # shellcheck source=/dev/null
 source "$SCRIPTS_DIR/lib/$module.sh"
done
# shellcheck source=.claude/scripts/prompts.sh
source "$SCRIPTS_DIR/prompts.sh"

# ── Context: which tool call or commit triggered us ─────────────────────────
HOOK_COMMAND=""
if is_claude_hook_context; then
 if [ -n "$(missing_commands jq)" ]; then
   echo "Docs hook: jq is not installed, documentation skipped" >&2
   exit 0
 fi
 HOOK_COMMAND=$(read_claude_tool_command)
 # A Claude Code tool call that is not a git commit: nothing to do.
 if [ -n "$HOOK_COMMAND" ] && ! is_git_commit_command "$HOOK_COMMAND"; then
   exit 0
 fi
 # A commit in another repository (cd other && git commit, git -C other commit) is that
 # repository's business: its own native hook documents it, if installed.
 if [ -n "$HOOK_COMMAND" ] && ! commit_runs_in_repo "$HOOK_COMMAND" "$HOOK_START_DIR" "$REPO_ROOT"; then
   echo "Docs hook: this commit does not run in $REPO_ROOT (or its directory cannot be determined), documentation skipped" >&2
   exit 0
 fi
fi
readonly HOOK_COMMAND

# ── Guard: commit already documented by the Claude Code hook (native hook only) ─
if [ -z "$HOOK_COMMAND" ] && consume_documented_tree_marker; then
 echo "Docs already generated by the Claude Code hook for this commit, skipping"
 exit 0
fi

# ── Guard: dependencies ──────────────────────────────────────────────────────
MISSING=$(missing_commands $PIPELINE_DEPENDENCIES)
if [ -n "$MISSING" ]; then
 echo "Docs hook: missing $MISSING, documentation skipped" >&2
 exit 0
fi

# ── Guard: staging inside the commit command (Claude Code only) ──────────────
# Must run before the nothing-staged guard: `git add . && git commit` on a clean index
# would otherwise exit silently without docs. Exit 2 blocks the tool call; stderr goes to Claude.
STAGING_REASON=$(staging_in_commit_command "$HOOK_COMMAND")
if [ -n "$STAGING_REASON" ]; then
 cat >&2 <<MSG
Docs hook: this commit stages files in the same command ($STAGING_REASON), so the
documentation hook cannot see what will be committed. Run the staging step as its own
Bash command (e.g. \`git add <files>\`, or \`git add -u\` instead of -a), then run
\`git commit\` on its own without -a/-i/-o/-p or file paths.
MSG
 exit 2
fi

# ── Guard: nothing staged ────────────────────────────────────────────────────
has_staged_changes || exit 0

# ── Generate the docs ────────────────────────────────────────────────────────
COMMIT_MSG=$(commit_message_from_command "$HOOK_COMMAND")
start_time_budget

WORK_DIR=$(mktemp -d 2>/dev/null) || exit 0

# Stop background jobs and remove temp files, however the hook ends.
cleanup() {
 local pid dir
 for pid in $(jobs -p); do
   kill_process_tree "$pid"
 done
 for dir in "${DOC_TARGET_DIRS[@]}"; do
   rm -f "$dir"/*.tmp.$$
 done
 rm -rf "$WORK_DIR"
}
trap cleanup EXIT
trap 'exit 143' INT TERM

collect_doc_targets "$REPO_ROOT"
run_doc_targets_in_batches "$WORK_DIR"

# Claude Code hook: tell the native pre-commit hook this exact staged tree is documented.
# Not written when blocked, killed, or when nothing was staged.
[ -n "$HOOK_COMMAND" ] && record_documented_tree

exit 0
